services:
  # Web Service (Backend + Frontend)
  - type: web
    name: dashtools
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false

